# config.yaml
# -----------
data:
  input_filepath: "data/full/full_reviews.csv"
  review_column: "review"
  timestamps_column: "yearMonth"
  sample_size: null  # Use null for all data

model:
  transformer_name: "all-MiniLM-L6-v2"
  language: "french"
  min_topic_size: 20
  nr_topics: "auto"
  umap:
    n_neighbors: 15
    n_components: 5
    min_dist: 0.0
    metric: "cosine"
  hdbscan:
    min_cluster_size: 15
    metric: "euclidean"
    cluster_selection_method: "eom"
    prediction_data: true
  vectorizer:
    stop_words: None
    ngram_range: [1, 2]

evaluation:
  coherence_metrics:
    - "c_v"
    - "u_mass"
    - "c_npmi"

output:
  save_model: true
  output_dir: "data/results"
  dashboard_port: 8050