# config.yaml
# -----------
data:
  input_filepath: "data/full/full_reviews.csv"  # Path to the CSV file
  review_column: "review"  # Column name for reviews
  timestamps_column: "yearMonth"  # Column name for timestamps
  sample_size: null  # Optional: Number of reviews to sample. Use null for all data 

model:
  transformer_name: "all-MiniLM-L6-v2"
  language: "french"
  min_topic_size: 20
  nr_topics: "auto"
  top_n_words: 10
  umap:
    n_neighbors: 15
    n_components: 3
    min_dist: 0.0
    metric: "cosine"
  hdbscan:
    min_cluster_size: 15
    metric: "euclidean"
    cluster_selection_method: "eom"
    prediction_data: true
  vectorizer:
    stop_words: None
    ngram_range: [1, 2]

evaluation:
  coherence_metrics:    # Coherence metrics to calculate
    - "c_v"
    - "u_mass"
    - "c_npmi"

output:
  save_model: true   # Whether to save the trained model
  output_dir: "data/results"  # Directory to save model outputs
  dashboard_port: 8050  # Port for the dashboard  